// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQLtz3O1jxmUc_9DYiMSaUkOMaCB-XHEA',
    appId: '1:678593423541:web:b5eeb5172330778720f6fc',
    messagingSenderId: '678593423541',
    projectId: 'tesororegional-d4fe7',
    authDomain: 'tesororegional-d4fe7.firebaseapp.com',
    storageBucket: 'tesororegional-d4fe7.firebasestorage.app',
    measurementId: 'G-GZGYHDN67B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkmo3RNsH1SAzOzWxUWfoZq4ghHSbPmC4',
    appId: '1:678593423541:android:06b2594b49f0c08820f6fc',
    messagingSenderId: '678593423541',
    projectId: 'tesororegional-d4fe7',
    storageBucket: 'tesororegional-d4fe7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRNuk6zcPRa1lEUY_bYoVw42CnhpOLuTU',
    appId: '1:678593423541:ios:d7cc0a9b793c926f20f6fc',
    messagingSenderId: '678593423541',
    projectId: 'tesororegional-d4fe7',
    storageBucket: 'tesororegional-d4fe7.firebasestorage.app',
    androidClientId: '678593423541-qmfp0ube79149vf469qhh50drgvebbuv.apps.googleusercontent.com',
    iosClientId: '678593423541-uc2fo2d87srlhb2gk2294g4chkd79vic.apps.googleusercontent.com',
    iosBundleId: 'com.tesororegional.tesororegional.tesoroRegional',
  );

}